---
title: "discretized_form"
output: html_document
date: "2023-05-25"
author: "Aïsha Schuhegger" 
Note: "Download and run all Rmd files from the github repository. You will need the ermerging results." 
---

```{r}
library(dplyr)
```


Create a new file (baesd on the data from the events file) where all the events belonging to the 'Included' or 'Excluded' cluster (regarding hclust) are excluded. 

```{r}
#Retained Intron 
cluster_RI_3_histo_hclust #AS cluster regarding RI (based on specific events from the events.csv file)

psi_RI_AS_1_df <- as.data.frame(psi_RI_AS_1_hclust)
psi_RI_AS_2_df <- as.data.frame(psi_RI_AS_2_hclust)
psi_RI_AS_3_df <- as.data.frame(psi_RI_AS_3_hclust)
psi_RI_AS_4_df <- as.data.frame(psi_RI_AS_4_hclust)
psi_RI_AS_5_df <- as.data.frame(psi_RI_AS_5_hclust)
psi_RI_AS_6_df <- as.data.frame(psi_RI_AS_6_hclust)

median_RI_AS_1 <- as.vector(quantile_RI_AS_1_hclust)
median_RI_AS_2 <- as.vector(quantile_RI_AS_2_hclust)
median_RI_AS_3 <- as.vector(quantile_RI_AS_3_hclust)
median_RI_AS_4 <- as.vector(quantile_RI_AS_4_hclust)
median_RI_AS_5 <- as.vector(quantile_RI_AS_5_hclust)
median_RI_AS_6 <- as.vector(quantile_RI_AS_6_hclust)

psi_RI_AS_1_df <- ifelse(psi_RI_AS_1_df > median_RI_AS_1[3], 1, 0)
psi_RI_AS_2_df <- ifelse(psi_RI_AS_2_df > median_RI_AS_2[3], 1, 0)
psi_RI_AS_3_df <- ifelse(psi_RI_AS_3_df > median_RI_AS_3[3], 1, 0)
psi_RI_AS_4_df <- ifelse(psi_RI_AS_4_df > median_RI_AS_4[3], 1, 0)
psi_RI_AS_5_df <- ifelse(psi_RI_AS_5_df > median_RI_AS_5[3], 1, 0)
psi_RI_AS_6_df <- ifelse(psi_RI_AS_6_df > median_RI_AS_6[3], 1, 0)


discretized_df_RI <- dplyr::bind_rows(as.data.frame(psi_RI_AS_1_df), as.data.frame(psi_RI_AS_2_df), as.data.frame(psi_RI_AS_3_df), as.data.frame(psi_RI_AS_4_df), as.data.frame(psi_RI_AS_5_df), as.data.frame(psi_RI_AS_6_df))
discretized_df_RI

#cluster_SE_1_histo_hclust #AS cluster regarding SE 
```

```{r}
#Skipped Exon 
cluster_SE_1_histo_hclust #AS cluster regarding SE 

psi_SE_AS_1_df <- as.data.frame(psi_SE_AS_1_hclust)
psi_SE_AS_2_df <- as.data.frame(psi_SE_AS_2_hclust)
psi_SE_AS_3_df <- as.data.frame(psi_SE_AS_3_hclust)
psi_SE_AS_4_df <- as.data.frame(psi_SE_AS_4_hclust)
psi_SE_AS_5_df <- as.data.frame(psi_SE_AS_5_hclust)
psi_SE_AS_6_df <- as.data.frame(psi_SE_AS_6_hclust)

median_SE_AS_1 <- as.vector(quantile_SE_AS_1_hclust)
median_SE_AS_2 <- as.vector(quantile_SE_AS_2_hclust)
median_SE_AS_3 <- as.vector(quantile_SE_AS_3_hclust)
median_SE_AS_4 <- as.vector(quantile_SE_AS_4_hclust)
median_SE_AS_5 <- as.vector(quantile_SE_AS_5_hclust)
median_SE_AS_6 <- as.vector(quantile_SE_AS_6_hclust)

psi_SE_AS_1_df <- ifelse(psi_SE_AS_1_df > median_SE_AS_1[3], 1, 0)
psi_SE_AS_2_df <- ifelse(psi_SE_AS_2_df > median_SE_AS_2[3], 1, 0)
psi_SE_AS_3_df <- ifelse(psi_SE_AS_3_df > median_SE_AS_3[3], 1, 0)
psi_SE_AS_4_df <- ifelse(psi_SE_AS_4_df > median_SE_AS_4[3], 1, 0)
psi_SE_AS_5_df <- ifelse(psi_SE_AS_5_df > median_SE_AS_5[3], 1, 0)
psi_SE_AS_6_df <- ifelse(psi_SE_AS_6_df > median_SE_AS_6[3], 1, 0)


discretized_df_SE <- dplyr::bind_rows(as.data.frame(psi_SE_AS_1_df), as.data.frame(psi_SE_AS_2_df), as.data.frame(psi_SE_AS_3_df), as.data.frame(psi_SE_AS_4_df), as.data.frame(psi_SE_AS_5_df), as.data.frame(psi_SE_AS_6_df))
discretized_df_SE

#cluster_SE_1_histo_hclust #AS cluster regarding SE 
```

Combine discretized_df_RI and discretized_df_SE
```{r}
discretized_df <- dplyr::bind_rows(discretized_df_RI, discretized_df_SE)
# Order the data frame based on row names
rownames_discretized_df <- as.vector(rownames(discretized_df))

# Order the data frame based on row names
discretized_df <- discretized_df[order(rownames_discretized_df), ]

#for (i in 1:nrow(discretized_df)){
#  rownames(discretized_df)[i] <- strsplit(rownames(discretized_df), ";")[[i]][1]
#}

#Duplikate handling? 

discretized_df
```

Now: 0.5 is the threshold for every event 
-> comparisson between discretized_df and discretized_05_df
```{r}
#cluster_RI_3_histo_hclust #AS cluster regarding RI
#cluster_SE_1_histo_hclust #AS cluster regarding SE

cluster_RI_3_histo_hclust <- as.data.frame(cluster_RI_3_histo_hclust)
cluster_SE_1_histo_hclust <- as.data.frame(cluster_SE_1_histo_hclust)

psi_RI_AS_05_df <- ifelse(cluster_RI_3_histo_hclust > 0.5, 1, 0)
psi_SE_AS_05_df <- ifelse(cluster_SE_1_histo_hclust > 0.5, 1, 0)


discretized_05_df <- dplyr::bind_rows(as.data.frame(psi_RI_AS_05_df), as.data.frame(psi_SE_AS_05_df))

rownames_discretized_05_df <- as.vector(rownames(discretized_05_df))

# Order the data frame based on row names
discretized_05_df <- discretized_05_df[order(rownames_discretized_05_df), ]

```

Comparison between the data frames 

```{r}
common_values <- intersect(as.matrix(discretized_df), as.matrix(discretized_05_df))
common_count <- length(common_values)
common_count
# -> 3 values are the same (possible?)
```

